@startuml usecase
    left to right direction
    actor Камера
    actor Сервер
    actor Робот

    package Обнаружение_объектов {
        usecase "Определение координат робота" as коорд_роб
        usecase "Определение координат граффити" as коорд_графф
        usecase "Определение координат препятствия" as коорд_преп
    }

    package Движения_робота {
        usecase "Двигаться вперед" as вперед
        usecase "Двигаться назад" as назад
        usecase "Двигаться влево" as влево
        usecase "Двигаться вправо" as вправо
        usecase "Остановиться" as остановиться
    }

    Камера --> (Сделать фото)
    (Сделать фото) --> Сервер : Передача фото на сервер

    Сервер --> (Перекодирование фото в .bmp)
    (Перекодирование фото в .bmp) -left-> коорд_роб
    (Перекодирование фото в .bmp) -left-> коорд_графф
    (Перекодирование фото в .bmp) -left-> коорд_преп
    коорд_роб --> (Построение маршрута)
    коорд_графф --> (Построение маршрута)
    коорд_преп --> (Построение маршрута)
    (Построение маршрута) --> Робот : Передача маршрута роботу

    Робот --> вперед
    Робот --> назад
    Робот --> влево
    Робот --> вправо
    Робот --> остановиться
    вперед --> Сервер : возврат состояния
    назад --> Сервер : возврат состояния
    влево --> Сервер : возврат состояния
    вправо --> Сервер : возврат состояния
    остановиться --> Сервер : возврат состояния
@enduml