@startuml order_of_cases
    participant Камера
    actor Сервер
    participant Робот

    Камера -> Сервер : Изображение
    Сервер -> Робот : Маршрут
    Робот -> Робот : Выполнение
    Робот -> Сервер : Состояние
@enduml